### ISSUE TITLE
Auto Run/Walk

### ISSUE THREAD

**Issue by NeoGreen22** [VORPCORE/vorp_inventory-lua#117]
If you open inventory when walking or running you are stuck in that state and cant stop moving, requires to open menu up multiple times to sometimes fix it or its possible you cant stop at all. Forcing a logout.

**Comment by outsider31000** [comment]
Justlike with any NUi if you try with chat same thingit locks what you doing

**Comment by NeoGreen22** [comment]
Allright np, thanks for information.
