### ISSUE TITLE
not saving durability of item when moved to inv to stash / horse 

### ISSUE THREAD

**Issue by RealStonerGamer** [VORPCORE/vorp_inventory-lua#128]
when you put i item that had durability at like 99 or lower on a horse or in a stash our house inv it will reset back to a bran new item not damaged and not keeping the durability it had

**Comment by outsider31000** [comment]
this is nothing to do with inventory.  what scripts you use for horse ? housing? statsh?

**Comment by outsider31000** [comment]
they need to be able to handle metadata

**Comment by RealStonerGamer** [comment]
> they need to be able to handle metadata
Syn and vorp scripts

**Comment by RealStonerGamer** [comment]
is there a way to disable durability on these items? i cant find a way to ...

**Comment by BurntJannings** [comment]
Having the same problem with society inventories it looks like, house seem fine i think, will be testing blues latest push of society in about an hour and will report back what i find

**Comment by RealStonerGamer** [comment]
OK if there was a patch i will have to have my server owner download it

**Comment by outsider31000** [comment]
> > they need to be able to handle metadata
> > Syn and vorp scripts

what vorp scripts ?

syn go to his discord. this is nothing to do with inventory

**Comment by outsider31000** [comment]
report to his discord,  I say this once and for all SYN SCRIPTS have nothing to do with VORP.

**Comment by RealStonerGamer** [comment]
> report to his discord, I say this once and for all SYN SCRIPTS have nothing to do with VORP.

no need to be so rude... im just trying to figure this out I'm sorry I'm not a genius coder like you guys I'm new to all this and had no clue it was there issue when i thought the dam inv was the issue ... its a simple mistake and as soon as i  was told  that the other script was the issue i said ok and left it at that no need to be rude and yell  if your stressed or upset just don't say any thing and take a brake don't take it out on people trying to learn and get help

**Comment by outsider31000** [comment]
im not being rude if thats how you understand thats your problem. 
 this is not fivem this is for mature people not for kids
 
youre not trying to learn nothing youre here reporting stuff, and this has nothing to do with YOU being NEW
its COMON SENSE 
if you use other scripts for housing wagons horses etc how does this has to do with vorp?

lastly the message was for everyone.
