### ISSUE TITLE
CAN DROP AND GIVE ITEMS INTO DECIMAL?

### ISSUE THREAD

**Issue by rmrsnpdr** [VORPCORE/vorp_inventory-lua#14]
You can drop items and give to make it decimal in your inventory so it will be unlimited to use.

**Comment by rmrsnpdr** [comment]
![image](https://user-images.githubusercontent.com/106513621/170940751-763780ae-2f71-4dbb-9ad8-b547972323ee.png)

**Comment by outsider31000** [comment]
We will look into it

**Comment by rmrsnpdr** [comment]
okay cause when the item turned into decimal u can use it anytime and it will never be remove on your inventory.

**Comment by rmrsnpdr** [comment]
oh i see. okay ill wait
