### ISSUE TITLE
Can't run . No Such Export vorp_inventoryApi

### ISSUE THREAD

**Issue by Nabusius** [VORPCORE/vorp_inventory-lua#16]
Hi . 
I installed the script at this place : resources\\[core]\\vorp_inventory
but when i try to launch it i have this error : 
```
[    c-scripting-core] Creating script environments for vorp_inventory
[script:vorp_inventor] Error loading script server/server.lua in resource vorp_inventory: citizen:/scripting/lua/scheduler.lua:867: No such export vorp_inventoryApi in resource vorp_inventory
[script:vorp_inventor] stack traceback:
[script:vorp_inventor]  [C]: in function 'error'
[script:vorp_inventor]  citizen:/scripting/lua/scheduler.lua:867: in metamethod '__index'
[script:vorp_inventor]  @vorp_inventory/server/server.lua:7: in main chunk

```
Can someone help me or tell me what wrong i do ?

**Comment by outsider31000** [comment]
vorp_inventory it's the name of the  folder

**Comment by Nabusius** [comment]
I don't understand ? 
My folder is vorp_inventory : https://imgur.com/a/1oCf0zs

**Comment by outsider31000** [comment]
this is the repo 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/87246847/171283196-bcb4f65a-7433-4f94-81f0-d8a861e44d10.png">
 now please compare and update

**Comment by outsider31000** [comment]
also if you keep changing things they wont work 
<img width="45" alt="image" src="https://user-images.githubusercontent.com/87246847/171283340-9b005441-b858-4e85-bd34-88e1463adbb2.png">
 this is not on the premade. which would not break but assuming you changed this idk why you prob you changed other things too

**Comment by Nabusius** [comment]
Ok i updated from your repo , i move all vorp_ on ressources  but same problem

**Comment by Nabusius** [comment]
https://imgur.com/a/5vWf6Yq

**Comment by Nabusius** [comment]
I changed nothing on VORP_Core (lua) or other VORP script ... So i don't understand why its not working

**Comment by outsider31000** [comment]
download premade server

**Comment by Nabusius** [comment]
if your script only work with the premade build its a problem xD

**Comment by Nabusius** [comment]
I do nothing Vorp Core lua works perfectly , Vorp Character Works Perfectly and Vorp Inventory Don't work i do nothings xD
