### ISSUE TITLE
The latest changes are causing this for me.

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_inventory-lua#160]
![Screenshot_19](https://user-images.githubusercontent.com/101003021/230948791-9814c88e-c89b-49bd-a678-8507f3488cca.png)
![Screenshot_20](https://user-images.githubusercontent.com/101003021/230948792-ce07bf14-a0e4-4218-8f51-30bbf2a78144.png)

**Comment by outsider31000** [comment]
did you update both files?
