### ISSUE TITLE
Amount of received money not shown

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#165]
If you give money to an other player, this player didn't see how much he gets. This opens the possibility to cheat, if I didn't look how much money I have before the transaction.
![money](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/f379b93a-b5be-49fd-ad1f-5b4e534d215f)

**Comment by outsider31000** [comment]
the amounts are shown, maybe update the script
