### ISSUE TITLE
Weapons cannot be equipped after a swap.

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_inventory-lua#175]
https://streamable.com/jn588c

The entire inventory system was tested using the inventory script directly from GitHub without making any modifications. The issue encountered is as follows: after equipping two weapons, storing them in the inventory, and retrieving two different weapons, the newly obtained weapons cannot be used anymore. For more information and to see the problem firsthand, please refer to the provided video and the error message displayed in the F8 console.

**Comment by outsider31000** [comment]
what is this script you using for the secondary inventory ?

**Comment by outsider31000** [comment]
its the same thing with any secondary inventory ? 
seems to be an issue with dual weapons , i will try to replicate

**Comment by DerHobbs** [comment]
> 

syn_society

It's the same with the horse with the saddlebags (gum_stable) and storage boxes, where we use the custom inventory

thanks for looking

**Comment by outsider31000** [comment]
this should be fixed , test...

**Comment by DerHobbs** [comment]
I had 2 lemat equipped, put them in and wanted to pick up a Cattelman, then this error comes up.

![Screenshot 2023-07-22 115846](https://github.com/VORPCORE/vorp_inventory-lua/assets/101003021/b14c3bd5-c022-4104-bba5-eada6295911d)

**Comment by outsider31000** [comment]
put them in where? and pick up a catlle man from the floor ?

**Comment by outsider31000** [comment]
try update again.

**Comment by outsider31000** [comment]
@DerHobbs

**Comment by DerHobbs** [comment]
Work!
