### ISSUE TITLE
New Character check seems to not work anymore 

### ISSUE THREAD

**Issue by RealStonerGamer** [VORPCORE/vorp_inventory-lua#176]
with new vorp_character-lua and vorp_inventory the check for if your a NewPlayers = true is not working they can all trade items weps and money or gold   

this was on a character that was made 2 mins before the trade 

![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/eaae0e38-018a-4ad9-a4a3-7f236ec5dbe7)

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/bf880d36-b11a-4334-abec-ec182f5569c3)
needs to be true

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/7307b7c7-f725-4a24-a05b-7ce835b357a4)
if its false cant give

**Comment by RealStonerGamer** [comment]
it is true 

![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/2b8f9b39-149d-4a1b-b2f9-86bfb3c16f17)
 that is what im saying 
 its true and still can give

**Comment by outsider31000** [comment]
i said false

**Comment by outsider31000** [comment]
if you want them not to be able to give items or money as new players needs to be true

but as you see in the code 
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/10a4bd3a-5433-463a-ab1a-4fae162a5531)
all is good if its true it will work

**Comment by RealStonerGamer** [comment]
it's not working though that is what I'm saying ...  i have it set to true and i have tried setting it to false and its still not working  it always allows to trade  i have tried set to true and tried set to false bot do not work ... so its bot working

**Comment by RealStonerGamer** [comment]
> if you want them not to be able to give items or money as new players needs to be true
> 
> but as you see in the code ![image](https://user-images.githubusercontent.com/87246847/254082707-10a4bd3a-5433-463a-ab1a-4fae162a5531.png) all is good if its true it will work

this is what im saying it looks fine but its not working...

**Comment by RealStonerGamer** [comment]
this just makes no sense to me it looks like it should be fine but dose not seem to be working ... is the trigger from 'vorp_Character'  when you make your character is  working right ? you think that might be it ?

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/c3a0e1c1-edb9-4b55-9fe8-0625ff9106d8)
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/19cf2fb9-4879-4cf5-ab52-7b7404072f54)

**Comment by RealStonerGamer** [comment]
> 

yes i see its set fine but again then why is it not working when set in config   NewPlayers = true 
?

**Comment by RealStonerGamer** [comment]
ill video it when i can tonight and show you what i mean ...

**Comment by RealStonerGamer** [comment]
> ![image](https://user-images.githubusercontent.com/87246847/254087973-c3a0e1c1-edb9-4b55-9fe8-0625ff9106d8.png) ![image](https://user-images.githubusercontent.com/87246847/254088159-19cf2fb9-4879-4cf5-ab52-7b7404072f54.png)

i added a print and it come back nil 
and to make sure it was triggering 
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/fd158c4d-97c9-4272-89ac-58deed115147)
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/ede5ac96-5f64-479d-a615-f888e5df2350)
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/778980d5-e222-48be-88c9-791eb1f5ab9b)

**Comment by RealStonerGamer** [comment]
so i added a wait(2000) here  and  now its not nil so i think its just runing to fast befor the ID is made 

![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/f3d3a7a1-0c49-49f3-9637-22406226b844)
```

AddEventHandler('vorp_NewCharacter', function(source) 	
	local _source = source
	Wait(2000)                   -- new wait need to beable to get the charid 
	local Character = Core.getUser(_source).getUsedCharacter
	local charid = Character.charIdentifier
	print(charid)
	table.insert(newchar, charid)
	Wait(timer * 60000)
	for k, v in pairs(newchar) do
		if v == charid then
			newchar[k] = nil
		end
	end
end)
```

![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/26008458/9dcb9b0f-c764-4b58-ac38-3ae68411eec5)



so we just need a wait(2000) added and the check will work fine for money and items are working fine now but the WEAPON's can be given still

**Comment by outsider31000** [comment]
thanks i have added a wait but in characters before sending that event to make sure char is created in time

**Comment by RealStonerGamer** [comment]
sounds good now just need to figure out why you can still trade weapons

**Comment by outsider31000** [comment]
it was missing it was added now

**Comment by RealStonerGamer** [comment]
All is working fine thanks a lot ! this is good to close now man
