### ISSUE TITLE
Deposited Weapons Vanishes in Custom Storages

### ISSUE THREAD

**Issue by d-pruessmeier** [VORPCORE/vorp_inventory-lua#179]
Deposited Weapons are invisible to other players if the player who deposited the weapon disconnects from the server. Items working normaly

**Comment by JulianLegler** [comment]
Can confirm. We are able to reproduce this error. 

Its based on how loadouts are loaded in 
https://github.com/VORPCORE/vorp_inventory-lua/blob/2cdfa47b96077958bab79da612b57f6662f6a575/server/services/itemsDatabase.lua#L20

As loadouts are solely loaded when the player select event is triggered
https://github.com/VORPCORE/vorp_inventory-lua/blob/2cdfa47b96077958bab79da612b57f6662f6a575/server/services/itemsDatabase.lua#L67
the deposited weapons of players that are not logged in, are not visible. 

Reproduce steps:
1. Player A is putting a Weapon into a shared inventory, Player B can confirm that the Weapon is there and visible.
2. Restart the server.
3. Player B connects and looks in the shared inventory.
4. The weapon is missing.
5. Player A connects.
6. Player B looks in the shared inventory and the weapon is in the shared inventory.


Possible Fix:
1. Load all weapons on server start. (performance?)
2. Load all weapons on server start that are not in the "default" inventory
3. Load all weapons from a custom inventory when accessing it the open inventory and add in the function where all items are loaded on openCustomInventory (https://github.com/VORPCORE/vorp_inventory-lua/blob/2cdfa47b96077958bab79da612b57f6662f6a575/server/services/inventoryApiService.lua#L1366C14-L1366C34)

**Comment by outsider31000** [comment]
@JulianLegler @d-pruessmeier  can yall test this version now see if it works with new changes please

**Comment by outsider31000** [comment]
test this or ill just close it @JulianLegler

**Comment by JulianLegler** [comment]
@outsider31000 we tested your fix and it works as expected. Thanks for your work.
