### ISSUE TITLE
Inventory-Tab medicine and herbs

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#181]
When I open a secoundary inventory (here inventory of a wagon) and I click "medicine" or "herb" icon on the right sight, it changes my inventory on the left side. Other icons work fine. (see picture). Further I found out, that in an inventory of syn_society the icons not shown.
![inventory2 8](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/f40d628c-24f1-4dcb-8653-b67b512fa0d6)
![society_inventory2 8](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/1c10e795-d952-449f-960a-494b2d916f07)

**Comment by outsider31000** [comment]
your first issue , idk what stables is that ,  with custom inventories they do work.

the second issue the buttons are there but hidden , none of syn scripts will have the items type to work untill he makes changes to adpat to his scripts.

**Comment by VarusXX** [comment]
> your first issue , idk what stables is that , with custom inventories they do work.
That is gum_stables 
> the second issue the buttons are there but hidden , none of syn scripts will have the items type to work untill he makes changes to adpat to his scripts.
Thank you

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/e98a25b6-8fe2-4527-8a06-77818ed0266f)
syn scripts will now show the buttons but the functionality wont work as he needs to implement it in his scripts

**Comment by outsider31000** [comment]
as for the first issue i do not have that with custom inventories so ill be closing this issue. maybe try update .

**Comment by outsider31000** [comment]
you were right, its fixed for issue number 1 update
