### ISSUE TITLE
IDEA : Better view of inventory items

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_inventory-lua#183]
A better and easier way to see who has what in their inventory. At the moment you have to look and search in 2 or 3 different tables which makes it very cluttered and makes more data in my opinion. An option in the admin menu to view someone's inventory in game also seems very useful to me.

**Comment by outsider31000** [comment]
at the moment theres no API to open someones inventory, the admin menu already can check a list of items and weapons in databse option.
