### ISSUE TITLE
Error in fxmanifest.lua

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#185]
When ammo.lua and weapons.lua is moved to /config foulder, you should state this in fxmanifest.lua. If not you will get this:
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/1cf83975-39e2-4648-b060-2ff27a6f11a1)

[...]
shared_scripts {
  "config/*.lua",
  "languages/*.lua",
  "shared/models/*.lua",
  'shared/handler/*.lua',
  "shared/services/*.lua",
  "shared/services/Regex.js",
  'config/weapons.lua', 
  'config/ammo.lua'
}
[...]

BTW: In fxmanifest.lua you are useing "..." and '...' for what reason?

**Comment by VarusXX** [comment]
When I fix the path in fxmanifest.lua to
'config/weapons.lua',
'config/ammo.lua'
I still get this error:
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/aaa9a0e9-2197-4b42-8937-aa45c8dda452)

**Comment by outsider31000** [comment]
its fixed.
