### ISSUE TITLE
Issue after restarting resource that use vorp_inventory 

### ISSUE THREAD

**Issue by zVoxty** [VORPCORE/vorp_inventory-lua#186]
After the update, there is an issue with the resources that use vorp_inventory after it is restarted
Steps to reproduce:
1. Register an item in the server.lua with:
VorpInv.RegisterUsableItem('lumberaxe', function(data)
	print('work')
	VorpInv.CloseInv(data.source)
end)

2. Restart the respective resource and then it will work properly after using the item
3. Restart the respective resource one more time and you will see the below error when double clicking the respective item.
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/17491952/fdea597e-cc77-4d22-96d9-7ef7829890fa)

PS: After restarting the server it works but for development, it is a pain because I need to restart the server every time.

**Comment by outsider31000** [comment]
i do not find any issues in restarting resources , you cant restart inventory without restarting the scripts that depends on it
