### ISSUE TITLE
Take a weapon from secondary inventory

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#187]
When I wants to take a weapon from secondary inventory (gum_camping) I will get this error. Maybe it could be a problem of gum_camping. Just to be sure.
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/9d9704e3-f11b-45fc-aa44-a5e29896d62e)
I didn't have this error with vorp_inventory 2.8

**Comment by DerHobbs** [comment]
I have the same problem, also with all other scripts, seems to be an inventory problem.

**Comment by outsider31000** [comment]
should be fixed
