### ISSUE TITLE
Item given to player

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_inventory-lua#188]
It is no longer possible to transfer items to other players.

This message appears in f8, nothing more happens, the item is not handed over, there is no notification and it remains in the inventory.

![Screenshot 2023-08-20 190150](https://github.com/VORPCORE/vorp_inventory-lua/assets/101003021/109296ba-2e2d-4c16-9dce-eda034a3a6b8)

**Comment by outsider31000** [comment]
try now

**Comment by DerHobbs** [comment]
Trading works again, but...

Category assignment when receiving items

When I receive an item from another player, it's only listed in the inventory under the "default" category, and it's not displayed in the appropriate category.

**Comment by outsider31000** [comment]
try now

**Comment by DerHobbs** [comment]
Perfect, you're wonderful! :D

There's also a bug with the categories in the second inventory. I've made a video for you regarding this. For example, herbs are ONLY displayed in the Herbs category, but not in the default overview. Also, there's something odd with the symbols at the top, as you can see in the video.

https://streamable.com/7exnhg

**Comment by outsider31000** [comment]
its because they too close to each other i guess.

**Comment by outsider31000** [comment]
try now should be fixed the herbs, and thanks for taking your time to test.
