### ISSUE TITLE
Picking up money or items

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_inventory-lua#19]
When players die, their money drops, this money can usually not be picked up, nothing is displayed on the bottom right either, the bag is there, but that's all there is to it, it's similar with items if you find a box somewhere because someone threw something , you can't usually undo it! that's too bad.

**Comment by Bobertsawesome** [comment]
Item drop on death is still in the testing phase it seems, and I do believe a lot of these issues are being looked at.
