### ISSUE TITLE
Equiped weapons

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_inventory-lua#192]
The inventory doesnt let you know anymore if a weapon is equiped yes or no. If you have the same weapons its hard to tell which one to give

**Comment by outsider31000** [comment]
there was never such thing with double click, switch to false and it will show when you righ click.

**Comment by JustRoys** [comment]
> there was never such thing with double click, switch to false and it will show when you righ click.

Switch false in where?

**Comment by outsider31000** [comment]
where it says to use doubleclick

**Comment by JustRoys** [comment]
I dont mean the use botton but when you equiped a when and right clicked on the weapon there was a equiped label in there if you equiped that weapon. Right now its gone with the newer updates. Its easy for players if they have 2 of the same weapons with them so they know which one they equiped

**Comment by outsider31000** [comment]
without  double click you can see that. it doesnt show with double click to true. it never did.
