### ISSUE TITLE
Dropping items

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#197]
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/e8d200cd-db86-467b-958f-20087d4812ac)
I tried to drop some wood and got this error and a moving wheel. Could only reconnect
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/827aec12-1dc6-408d-9afa-6ea429728d4f)

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/6bee338b-cc9c-4549-ac23-5f9df71391d9)
update your script before creating issues.

**Comment by outsider31000** [comment]
I have updated the releases  on github which is probably where you downloaded it.
