### ISSUE TITLE
No update after opening the next inventory

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_inventory-lua#200]
I just updated the vorp_inventory. It shows the serial of the weapons.
![camping_inv](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/5bacdcd3-f854-480d-b19d-253c1657348b)
In my case it was a inventory of gum_camping, but anyway it came up with an error in F8
![error](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/b23f5148-8264-45a6-b95c-431240830280)
As next I go and open an inventory of syn_society and it still shows the content of the first inventory and also the same error again in F8
![error2](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/c29d0bc0-3b24-4e52-ab51-d8970469e21d)
As next I go to an syn_housing inventory and had still the first content. Then I checked a wagon of gum_stable
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/e9346a74-4051-4179-bfdb-4d37aa6c3b61)
Back to the housing inventory and now it shows the content of the wagon
![grafik](https://github.com/VORPCORE/vorp_inventory-lua/assets/48722973/2d0d4cbf-016b-4310-8bbd-fe915381756f)

**Comment by ZioMark13** [comment]
Exactly same issue for me, but with Syn_Society containers

**Comment by VarusXX** [comment]
I have also tested with syn_society container. Same issue. After login I started first with syn_housing and got an empty inventory. Then if done what is written above

**Comment by ZioMark13** [comment]
Update, he fixed it.

Watch the last vorp_inventory commit by Blue (syn) that will solve your issue

**Comment by VarusXX** [comment]
Thanks. I'll try now

**Comment by VarusXX** [comment]
It works. Thanks @Blue...only the drop-thing do not work, but this is not part of this issue

**Comment by ZioMark13** [comment]
> It works. Thanks @blue...only the drop-thing do not work, but this is not part of this issue

We have to wait for outsider to fix that, let's see when he's free
