### ISSUE TITLE
lose all my ammunition

### ISSUE THREAD

**Issue by CaptainValaak** [VORPCORE/vorp_inventory-lua#203]
Since the update, when I put ammunition in my weapons, once I disconnect and reconnect I lose all my ammunition in the weapons

**Comment by JustRoys** [comment]
Got the same issue. Outsider said not the inventory but it's mostly it is because it is after the update

**Comment by outsider31000** [comment]
But i dont have the issue so it cant be from inventory.  Code either works or it doesnt, i have shown proof it works.

**Comment by JustRoys** [comment]
> Since the update, when I put ammunition in my weapons, once I disconnect and reconnect I lose all my ammunition in the weapons

What weapon script do you use?

**Comment by outsider31000** [comment]
give me steps , make a video, so i can follow the same thing to test.

**Comment by outsider31000** [comment]
this has been fixedd
