### ISSUE TITLE
Issue when buying guns or giving guns ( with admin)

### ISSUE THREAD

**Issue by smokezG** [VORPCORE/vorp_inventory-lua#205]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/147995290/5a7aa45a-2674-40d2-8e46-f408b6be872b)

**Comment by smokezG** [comment]
The menus works , but when I go to gun shops and buy guns it takes my money and gives me nothing

**Comment by outsider31000** [comment]
the error says you missing columns, in which were listed to add in the discord. are you not in the discord ?

**Comment by smokezG** [comment]
Ah so , the database is old?

**Comment by smokezG** [comment]
Drop me a link for discord

**Comment by outsider31000** [comment]
its in the profile of this organisation

**Comment by smokezG** [comment]
Good , thank you for support ! I will close the issue due is just a missing

**Comment by smokezG** [comment]
Have a nice day!
