### ISSUE TITLE
Item amount not updated correctly on not shared custom inventories

### ISSUE THREAD

**Issue by JulianLegler** [VORPCORE/vorp_inventory-lua#211]
There is a bug that causes an inconsistent state between the players in game inventory and the database state because updated amounts for an existing item stack are not correctly saved to the database when using not shared custom inventories. 

1. Create a new not shared inventory - `registerInventory("invname", 200, false, false, true)`
2. Add 9 items into the inventory
3. quit and reconnect
4. Add 20 of the same item to the inventory, see that the stack size increases to 29
5. quit and reconnect
6. The stack size in players inventory is 9. The amount in the db table character_inventories is also 9

Technical problem description is in #208 

Video:
https://medal.tv/games/red-dead-2/clips/1CRtpkqYCmrsR1/d1337RVBqBrj?invite=cr-MSw2TlIsMTYzMzExMTA5LA

**Comment by outsider31000** [comment]
ok thanks i will test

**Comment by outsider31000** [comment]
this has been fixed. if you want to test, the items amount now get properly updated.
