### ISSUE TITLE
New characters do not receive starting weapons from Config.startWeapons

### ISSUE THREAD

**Issue by JulianLegler** [VORPCORE/vorp_inventory-lua#213]
**Describe the bug**
Newly created characters are not receiving the weapons specified in the `Config.startWeapons` table. The table is currently structured to only contain keys, and the weapon assignment function seems to be expecting a table with values.

**To Reproduce**
1. Create a new character.
2. Open the inventory to check for the starting weapons.
3. Observe that the starting weapons are missing.
4. Check the server console, which shows the error: `SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:903: attempt to call a nil value (method 'upper')`.

**Expected behavior**
A new character should have the starting weapons specified in the `Config.startWeapons` table present in their inventory upon creation.

**Configurations**
https://github.com/VORPCORE/vorp_inventory-lua/blob/0be56f69c9338823b0bbd95e9a03f13f03a49644/config/config.lua#L91-L93

**Current Behavior in Code**
The current implementation in `onNewCharacter` that is meant to give weapons to new players:
https://github.com/VORPCORE/vorp_inventory-lua/blob/0be56f69c9338823b0bbd95e9a03f13f03a49644/server/services/inventoryService.lua#L1233-L1235
It expects to iterate over Config.startWeapons and ignore all keys (_) and just use the values. But these are always empty because of the way startWeapons is filled.

**Possible Solution**
Modify the iteration in the `onNewCharacter` function to use the keys from the `Config.startWeapons` table:
```lua
for value, _ in pairs(Config.startWeapons) do 
   InventoryAPI.registerWeapon(source, value, {}, {}, {}, function() end) 
end
```

**Additional context**
- The line of the error in the console might off a bit because of debugging functions I added to find the bug
- The issue has been consistent across multiple character creations and server restarts.
- the error on :upper occures in the `registerWeapon` function is raised because the wepname is passed as an empty table and not a string.

**Comment by ZambrOvosky** [comment]
> The table is currently structured to only contain keys[...]
That doesn't seems right. The startWeapons table only contains **values** and "default" **keys**, otherwise you said.
```lua
startWeapons = {
	WEAPON_MELEE_KNIFE'
}
```
is equal to
```lua
startWeapons = {
	[1] = WEAPON_MELEE_KNIFE'
}
```
On my server, every player is receiving their knives. The problem you mentioned should be somewhere else.

**Comment by ZambrOvosky** [comment]
LLS Annotations shows the same: 
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/15342592/7231d716-a2a7-4193-a2c5-d5049e525591)

**Comment by outsider31000** [comment]
its an array , that contains strings, in which is required to create weapon, I dont see anything wrong with it in fact it could use ipairs thats the only thing i noticed

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/c29b9d86-ad66-4725-9e2b-f9f46460b7d1)
 newly create char

**Comment by JulianLegler** [comment]
Ah yes you are completly right. Seems that I accidentially fetched a wrong config with all the back and forth for the last issue using the old format for startWeapons which was:
```
startWeapons = {
    WEAPON_MELEE_KNIFE = {}, 
  },
  ```
  While looking in the wrong config in the wrong repository.
