### ISSUE TITLE
Duplicate items by fast click on confirm button and button name !

### ISSUE THREAD

**Issue by SirecStudio** [VORPCORE/vorp_inventory-lua#22]
If you have 4 water and give them to somebody by fast click on accept button , and fast click on player name ! He will receive 2-3 times 4 water ! :-\

**Comment by outsider31000** [comment]
yes, it is known this issue and we will work on it.

**Comment by SirecStudio** [comment]
Oh, ok ! I don't have read that issue here so i have posted ! on other version (not lua) is the same issue ?

**Comment by outsider31000** [comment]
it should be in both inventories yes. it uses same dialog
