### ISSUE TITLE
Export and API do not work

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_inventory-lua#226]
**Describe the issue**
With the current update only my player inventory works, everything else concerning saddlebags, society storage or storage crates does not work anymore, it does not open, neither by direct export nor by API call, who cool if someone would look over it.

**To Reproduce**
Yes, download the inventory from Github and try it.

**Expected behavior**
The exports.vorp_inventory:vorp_inventoryApi() or exports.vorp_inventory:openInventory(source, invId) works again

**Screenshots**
None

**Additional context**
None

**Comment by outsider31000** [comment]
@RizzooTv  should work now.
