### ISSUE TITLE
label extends beyond the inventory interface

### ISSUE THREAD

**Issue by DeVerino-DVR** [VORPCORE/vorp_inventory-lua#229]
Describe the issue
After updating the Vorp Inventory, there's an issue with the weight display in the inventory. The "kg" label extends beyond the inventory interface.

To Reproduce

Navigate to the inventory section.
Observe the weight display area.
Notice that the "kg" label extends beyond its designated space.
Expected behavior
The weight display, including the "kg" label, should fit within its allocated space in the inventory interface without extending beyond the boundaries.

Screenshots
https://cdn.discordapp.com/attachments/723512745638625332/1232274752195006484/image.png?ex=6628dccb&is=66278b4b&hm=1119ec25e6ed1a990a5d2f80f502e7c874f60a115814d5f05c7916240ad4b029&

Additional context
This issue occurred immediately after updating to the latest version of the Vorp Inventory.

**Comment by outsider31000** [comment]
i'll adress this shortly

**Comment by DeVerino-DVR** [comment]
Yes everything works thank you @outsider31000
