### ISSUE TITLE
cant register the same item twice 

### ISSUE THREAD

**Issue by yaboibutt3r** [VORPCORE/vorp_inventory-lua#234]
For some reason since updating I've been getting this message on my live console - [script:vorp_inventor] Warning: item    bandage  is already registered,  cant register the same item twice 
[script:vorp_inventor] Info: if you restarting a script this is normal and you can ignore it!. it happens on server restart and wasn't doing it prior to updating but it doesnt make sense cause it seems like its trying to send the bandage sql to the database.. I dunno I could be completely wrong

**Comment by outsider31000** [comment]
no its telling you you have 2 scripts registering the same item twice, or one script doing it 2 times

**Comment by yaboibutt3r** [comment]
thanks for the help I'm fairly new to this and trying to make a well working server, looked through a few scripts and saw it was indeed registered on another script that i updated, removed the lines and problem solved.

**Comment by outsider31000** [comment]
yeah the prints are there to help you configure your server and see whats wrong with it, before everything was just hidden, they are a great help.
some people want to hide the prints lol.

**Comment by yaboibutt3r** [comment]
I think they're great cause I want as little error as possible and my knowledge in scripting is very minimal, Great work!
