### ISSUE TITLE
Inventory ammo bugs

### ISSUE THREAD

**Issue by yaboibutt3r** [VORPCORE/vorp_inventory-lua#236]
Hi, so I haven't been able to find every issue with the ammo yet but I just updated it and one of the main issues im finding is half of the ammunition (mostly the special types like slugs instead of normal shells) don't load into the gun when you try to load it, once you get a gun to load there is a issue with it not wanting to reload so after the gun runs out of ammo its useless cause it wont load again... no errors show on live console or f8 player console. just wanted to let you know so you could look into it!

**Comment by outsider31000** [comment]
you cant reload weapons once goes to 0 ? have you use the ammo again ?

**Comment by yaboibutt3r** [comment]
Yeah sorry for the bad explanation but lets say I had 5 rounds left in the gun and shot them all, when I open the inventory and try to load more ammo it doesn't do anything so I try again and it says stop spamming, its odd though cause I'm not getting any errors in console and sometimes it will work fine and load the gun but majority of the time its just acts weird and again some of the ammos just don't work at all so that may effect it too. I'm sorry if I've caused any confusion just wanted to share the bugs I encountered!

**Comment by outsider31000** [comment]
I just tested,  went 0 ammo and just add more ammo and have no issue?

**Comment by OhPapaOg** [comment]
I am having the same issue. I updated everything and still have this problem

**Comment by outsider31000** [comment]
I dont see any issue neither i see anyone complaining of it, there was an issue but it has been fixed. so ill close this , feel free to open if anyone has steps of reproduction so we can follow them
