### ISSUE TITLE
Deleting Characters will also remove items from shared inventories

### ISSUE THREAD

**Issue by JulianLegler** [VORPCORE/vorp_inventory-lua#239]
**Describe the issue**
When a character adds an item to a shared inventory and then the character is deleted from the DB, the items in the shared inventory are also gone. This behavior will be interpreted by the other Players using also this storage as "items are missing".

**To Reproduce**
1. Create new character Alice
2. open a shared inventory and add an item as character Alice
3. Connect with character Bob and open shared inventory
4. You see the added item from character Alice
5. Delete Character Alice
6. Restart Server
7. Connect with character Bob and open shared inventory
8. See that the inventory is missing the item from character Alice

**Expected behavior**
Items in shared inventories that can be accessed by others should not be deleted when the character is deleted.

**Additional context**
Regression added by this SQL query:

https://github.com/VORPCORE/vorp_inventory-lua/blob/7461a5ed04a0369850f09afe8643f16872d71c46/server/services/DbService.lua#L186C1-L189C5

Tested with this small script:
```lua
exports.vorp_inventory:registerInventory({
    id = "vorp_inventory_test",
    name = "Test Inventory",
    limit = 100,
    shared = true,
})

RegisterCommand("testinv", function(source, args, raw)
    local _source = source
    exports.vorp_inventory:openInventory(_source, "vorp_inventory_test")
end)
```

**Comment by outsider31000** [comment]
Yeah I guess I forgot that there is shared inventories.

**Comment by outsider31000** [comment]
Should be fixed now.
