### ISSUE TITLE
Server Crash with decimals

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/vorp_inventory-lua#26]
While on wagon, I tried to move 1.0 worth of an item.  It then stopped allowing me to move items from inventory to the wagon and vice verse then the server crashed. was able to replicate twice in a row.   Current version of inventory is installed

**Comment by outsider31000** [comment]
then dont do 1.0.  the correct value is `1 `

**Comment by EagLeTaLoN713** [comment]
until someone realises it or does it by mistake, thus crashing the server.....

**Comment by outsider31000** [comment]
then they learn how to add value.
 I could also make it so anyone using decimals gets automatically banned for trying to cheat because adding decimals that is not for MONEY is a cheat so crashing for adding a decimal is fair. lol

**Comment by EagLeTaLoN713** [comment]
What i mean is, someone does it by accident.  Finds out it crashes the server and uses it intentionally or tells a friend and they grief other servers.
