### ISSUE TITLE
AFTER CLEAR CACHE AND UPDATING TO THE LATEST INVENTORY.

### ISSUE THREAD

**Issue by rmrsnpdr** [VORPCORE/vorp_inventory-lua#27]
![image](https://user-images.githubusercontent.com/106513621/173214873-de388093-929e-4821-9594-62b0f80ecafc.png)

After clearing the cache and updating the inventory this happened. The inventory cant close and stuck in there.

**Comment by rmrsnpdr** [comment]
![image](https://user-images.githubusercontent.com/106513621/173217246-4d6a1cae-c176-476d-a053-c5c6c023dffc.png)

**Comment by outsider31000** [comment]
it says to update all files. INCLUDING HTML
