### ISSUE TITLE
Error when using the carriage and horse inventory

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_inventory-lua#31]
It doesn't always happen, but very often

https://prnt.sc/IEbdL_mW90-x

[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:145: attempt to index a nil value
[script:vorp_inventor] > ref (@vorp_inventory/vorpInventoryApi.lua:110)
[script:vorp_inventor] > handler (@vorp_inventory/server/server.lua:34)
[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/server.lua:49: attempt to index a nil value
[script:vorp_inventor] (nil stack trace)SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:145: attempt to index a nil value
[script:vorp_inventor] > ref (@vorp_inventory/vorpInventoryApi.lua:110)
[script:vorp_inventor] > handler (@vorp_inventory/server/server.lua:34)
[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/server.lua:49: attempt to index a nil value
[script:vorp_inventor] (nil stack trace)sync thread hitch warning: timer interval of 208 milliseconds

**Comment by outsider31000** [comment]
vorp stables?
or syn stables?

**Comment by DerHobbs** [comment]
syn stables
