### ISSUE TITLE
When giving items.

### ISSUE THREAD

**Issue by rmrsnpdr** [VORPCORE/vorp_inventory-lua#34]
When giving items the inventory takes time and has delay before it deduct in your inventory so there is time to use it before u give it to the player.

**Comment by rmrsnpdr** [comment]
The delay u can use the item while waiting for the item to be given.

**Comment by outsider31000** [comment]
Make a video.

**Comment by rmrsnpdr** [comment]
https://streamable.com/n1cbxd here

**Comment by SkazyPlayGames** [comment]
Same problem i try it.

**Comment by outsider31000** [comment]
Where's the duplication? It removes the items you have it doesn't duplicate

**Comment by outsider31000** [comment]
Therefore it's not a problem.

**Comment by rmrsnpdr** [comment]
but still you can use the item even tho u already gave it in my video i used the food twice even tho its only 1pc. its working on bullets too.

**Comment by outsider31000** [comment]
What is the quantity you have for boiled eggs? I cant see

**Comment by outsider31000** [comment]
we are looking into it thanks for reporting.

**Comment by AndrewR3K** [comment]
@rmrsnpdr Quick Development Update: Still working on the above PR, should be released this week. I am currently adding this fix to a few more inventory actions to prevent similar issues. Once these are in it will be ready to go and should resolve this issue.

**Comment by outsider31000** [comment]
I  believed this was fixed?
