### ISSUE TITLE
When withdrawn on ledger issue

### ISSUE THREAD

**Issue by philip1270** [VORPCORE/vorp_inventory-lua#41]
1 click on withdraw. then this error come up
![image](https://user-images.githubusercontent.com/52317299/175802299-cc3084fa-ea1f-4fd9-acc1-2941365eac8f.png)
![image](https://user-images.githubusercontent.com/52317299/175802309-afb87e35-2745-4e6e-9d6b-8e3e61f1ce57.png)
It withdrawn 3 times. no delay on server. cause to dupe the money
No discord ID displayed on the Bot too.

**Comment by rmrsnpdr** [comment]
i encountered this problem too.

**Comment by Maindefi** [comment]
Have you rectified your wallet?

**Comment by outsider31000** [comment]
update the scrip inventory

**Comment by rmrsnpdr** [comment]
i think the one that is causing this is the vorp_inputs.

**Comment by outsider31000** [comment]
The inputs does have nothing to do with it.
