### ISSUE TITLE
Revolver ammo not properly saving

### ISSUE THREAD

**Issue by TheViperTooth** [VORPCORE/vorp_inventory-lua#58]
So been doing some testing, loaded ammo into my revolvers (navy revolver and lemat revolver) while dual wielding and the ammo in the gun belt did NOT save after relogging, waited plenty of time to make sure a save occurred. tried again this time by just loading it into the Navy and relogging and it saved as long as I took out the navy first but IF I took out another revolver instead of the revolver I loaded it into it wiped my revolver ammo in the gun belt down to 1 or 0. Same thing occurred if I equipped the LeMat before I equipped a shotgun, ammo for the shotgun got reset down to 0. All files are freshly updated.

**Comment by outsider31000** [comment]
do you have the updated vorp weapons?

**Comment by DerHobbs** [comment]
I've just tested it, it works perfectly, when you shoot, the ammo is immediately updated in the database, what you describe can't be.

Update your inventory and weapons, make sure to replace all files.

**Comment by TheViperTooth** [comment]
All files are updated to recent release here's a clip of it, had loaded normal ammo into the navy revolver previously and pulled a LeMat out this time. So far it only seems to occur with normal ammo?
https://medal.tv/games/red-dead-2/clips/qokUgtB_JfOB5/d1337bG1ulKX?invite=cr-MSxTZEIsMzAwNDgzNzMs

**Comment by outsider31000** [comment]
<img width="146" alt="image" src="https://user-images.githubusercontent.com/87246847/176544776-4b283eb8-c7be-46fb-9f27-096564c1d97f.png">
<img width="197" alt="image" src="https://user-images.githubusercontent.com/87246847/176544816-aa025672-6678-4c4f-828e-5c2ce0c3c511.png">
 its working 
 
 i cant fix what i cant replicate

**Comment by TheViperTooth** [comment]
https://i.gyazo.com/thumb/1200/252f63083ef7a2631b227defa6e8988e-png.jpg
Still happening, if you wanna hop in a VC I can

**Comment by outsider31000** [comment]
hop on vc
