### ISSUE TITLE
No ammo load and error in server side

### ISSUE THREAD

**Issue by HonorAlterium** [VORPCORE/vorp_inventory-lua#65]
When i try to load ammunition into weapons it doesn't load and every time when a player join, i get this error in the console

![Screenshot_836](https://user-images.githubusercontent.com/15896773/177055232-f7ab2f6c-71e1-46a6-af94-1bfbafd74064.png)

**Comment by outsider31000** [comment]
show your characters tables

**Comment by HonorAlterium** [comment]
![Screenshot_837](https://user-images.githubusercontent.com/15896773/177055652-425dba02-49d2-440f-b46a-c054590ce54f.png)

**Comment by outsider31000** [comment]
we have discord for a reason. check the updates we do i always ping. we also have versions check for the same reason. update your script.

**Comment by HonorAlterium** [comment]
it is updated to the latest version here on github

**Comment by outsider31000** [comment]
check discord

**Comment by outsider31000** [comment]
i am not gonna say this to each person that is in vopr. i make announcements and ping everyone for a reason. so please check them and you will see whats missing

**Comment by HonorAlterium** [comment]
ok thanks a lot, i look immediately on the discord

**Comment by outsider31000** [comment]
any doubts use discord. this is something you missed. so ill be closing it
