### ISSUE TITLE
Ammo for gun resetting to zero by quickly equip/unequipping loaded weapons on character login

### ISSUE THREAD

**Issue by BulletJRP** [VORPCORE/vorp_inventory-lua#7]
When a player logs into the server and opens their inventory to unequip/equip their loaded weapons, sometimes the ammo count for one, possibly more, weapons will be set to zero.

I was able to reproduce this by attempting to equip a revolver while I was carrying a rifle in my hands already equipped.

No errors in client side console.

No errors in server side.

Bug shown in video @44 seconds.
https://youtu.be/toKFYnSqxPQ?t=37

**Comment by outsider31000** [comment]
tried to replicate this no luck.  i dont have the same as you

**Comment by BulletJRP** [comment]
re downloaded latest version. found difference and am running again. Thank you.

**Comment by BulletJRP** [comment]
Unfortunately this problem persists. It seems to happen when a player has a weapon equipped, quits, then joins again. When logging back in and unequipping and equipping the weapons. The ammo resets to zero on one of the weapons. There also seems to be something related to having 2 long rifles and a revolver.

**Comment by BulletJRP** [comment]
More testing
Test 1: (Litchfield Ammo disappearing on Lazo unequip)
https://medal.tv/games/red-dead-2/clips/j8ngm05oc36tw/d1337aXABVKQ?invite=cr-MSxyMnksNTc3OTc3NzAs

Test 2: (Volcanic Ammo disappearing on Inventory closing)
https://medal.tv/games/red-dead-2/clips/jbAELTyy6wf4O/d1337sLw06ae?invite=cr-MSxTMjUsNTc3OTc3NzAs

Test 3: (Slower, waiting No ammo disappearing.)
https://medal.tv/games/red-dead-2/clips/jbPaJdbUDpUop/d1337jLmbzKA?invite=cr-MSxUaEEsNTc3OTc3NzAs

Test 4: (Unequipping/Equipping as soon as logged in. Litchfield ammo lost when unequipping it.) [Extra points for being sent to the cursed spawn. 💀]
https://medal.tv/games/red-dead-2/clips/jbRFH8f0ihQ-7/d1337ZivHIsO?invite=cr-MSxEOUksNTc3OTc3NzAs

Test 5: (Unequipping **BEFORE** logout. Equipping as soon as logged in. No ammo loss. Seems consistent.)
https://medal.tv/games/red-dead-2/clips/jbSLYy1eomlra/d1337rMRUdaZ?invite=cr-MSxLMXcsNTc3OTc3NzAs

Test 6: (Waiting Litchfield ammo disappeared on unequip. Not consistent.)
https://medal.tv/games/red-dead-2/clips/jc4cVcWEbJEP4/d1337sSzKx0H?invite=cr-MSxxVkksNTc3OTc3NzAs

**Comment by outsider31000** [comment]
I will try to replicate this.  We have no complaints about it. So maybe you have a script in conflict. But i will try to replicate.

**Comment by SkazyPlayGames** [comment]
I have the same problem with improved bow.... After logout .

**Comment by BulletJRP** [comment]
this reoccurring issue seems to happen when a player logs out while having their guns equipped. The way we don't have the ammo disappear is to ensure players unequip all guns first before attempting to equip another gun.
