### ISSUE TITLE
Vorp_inventory - picked up items are broken (metadata branch)

### ISSUE THREAD

**Issue by DintyGadget** [VORPCORE/vorp_inventory-lua#76]
If you throw an item on the floor and pick it up again. The item loses all functions except "use". 

If the player rejoins the server, the item will "fix"

Before drop
![image](https://user-images.githubusercontent.com/25077548/179447670-a42c8c60-d2a1-4943-97c3-e2b866dab3c2.png)

After drop
![image](https://user-images.githubusercontent.com/25077548/179447734-bae3f406-1de9-4169-b7a3-a164b2e1b323.png)

**Comment by RomainJolidon** [comment]
Found the reason. A fix is coming soon

**Comment by DintyGadget** [comment]
Fixed: c7c1fd58488100f4ea0013413e51f9195356b59a
