### ISSUE TITLE
DBupdater faill

### ISSUE THREAD

**Issue by evrp** [VORPCORE/vorp_inventory-lua#87]
[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/services/dbUpdater.lua:102: attempt to call a nil value (field 'dbUpdateAddTables')
[script:vorp_inventor] > fn (@vorp_inventory/server/services/dbUpdater.lua:102)

**Comment by AndrewR3K** [comment]
PR is up that should resolve this issue
